### ISSUE TITLE
Create Header to match the design guide

### ISSUE THREAD

**Issue by sonofab1rd** [cdierkens/bluebird-cabinetry-and-design#84]

**Comment by cdierkens** [comment]
**Nav links**
- Quicksand (TW: font-sans)
- Bold (TW: font-bold)
- Tracking -25 (TW: tracking-tight)
- Color #0f4c81 (TW: blue-dark)
- Padding: 16px (TW: p-4)
- Margin Top/Bottom: 16px (TW: my-4)
- Margin Left/Right 24px (TW: mx-5)

We'll need to figure out the hover effect for Nav Links

**Logo**
- [Image](https://user-images.githubusercontent.com/4812409/80328792-9dac1e80-87fd-11ea-8335-657ef054b7cc.png)
- Background #0f4c81
- Bottom Radius 6px (TW: rounded-b-md)
- Padding 36px (TW: p-9, let's extend the config and add this at 2.25rem)
- From rendered image to 128 x 120
- Total Box size should end up being around 200 x 176

**Comment by cdierkens** [comment]
**Button**
- Open Sans (TW: font-body)
- Semi-bold (TW: font-semibold)
- Border Radius 6px (TW: rounded-md)
- Border Color #0f4c81 (TW: border-blue-dark)
- Color: #0f4c81 (TW: font-blue)
- Padding Top/Bottom 12px (TW: py-3)
- Padding Left/Right 36px (TW: px-9)
- Font Size 20px (TW: text-xl)

@sonofab1rd See above

**Comment by sonofab1rd** [comment]
got a good start on this!

**Comment by cdierkens** [comment]
@sonofab1rd You might have a local commit that wasn't pushed!

**Comment by cdierkens** [comment]
@sonofab1rd I think it's gonna be a lot smoother to have a logo that has it's own whitespace around it. That way the whitespace scales with the image. Let's try this 
[image](https://user-images.githubusercontent.com/4812409/80722086-37a0ef00-8abc-11ea-8050-cade0bbd4752.png). (I just pulled this straight from the google drive)

Also, I think we can get a smoother effect if we have two logo sizes and we animate between them. So the once the user scrolls far enough we trigger the smaller scale.

Try this CSS on the LogoWrapper then toggle on and off scale in the dev tools:
```
transform: scale(0.5);
transform-origin: top;
transition-property: transform;
transition-duration: 500ms;
```

The CSS properties above should be translate to these Tailwind classes
https://tailwindcss.com/docs/transition-property/#app
https://tailwindcss.com/docs/transition-timing-function/#app
https://tailwindcss.com/docs/scale/#app
https://tailwindcss.com/docs/transform-origin/#app

Here's an article I found about using transform instead of animating height and width
https://pqina.nl/blog/animating-width-and-height-without-the-squish-effect/
